(define (yang-triangle n)
  (define (iter row column)
    (cond
     ((= row 1) 1)
     ((= column 1) 1)
     ((= column row) 1)
     (else (+ (iter (- row 1) (- column 1))
              (iter (- row 1) column)))))
  (define (iter2 row count)
    (write (iter row count))
    (write-char #\ )
    (if (not (= count 1))
        (iter2 row (- count 1))
        0))
  (define (iter3 count)
    (iter2 count count)
    (newline)
    (if (not (= count n))
        (iter3 (+ count 1))
        0))
  (iter3 1))
